modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="heart_plus"
version="1.0.0"
displayName="Heart PLUS"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="misosoup114514"
description="\u4F53\u529B\u304C\u5897\u3048\u308B\u30A2\u30A4\u30C6\u30E0\u3092\u8FFD\u52A0\u3057\u307E\u3059\u3002 Items to increase HP will be added."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.heart_plus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration